const RED = 'red';
const BLUE = 'blue';
const EMPTY = null;
const BLOCK = 'block';
const STARTRED = 'start-red'
const STARTBLUE = 'start-blue'
const ENDRED = 'end-red';
const ENDBLUE = 'end-blue'

export const defaultPuzzle = [
    [BLOCK, BLOCK, EMPTY, RED, EMPTY, BLUE, EMPTY, ENDRED],
    [BLOCK, BLOCK, EMPTY, BLOCK, BLUE, BLOCK, RED, BLOCK],
    [EMPTY, BLUE, EMPTY, RED, EMPTY, EMPTY, EMPTY, BLOCK],
    [EMPTY, BLOCK, RED, BLOCK, RED, BLOCK, EMPTY, BLOCK],
    [EMPTY, BLOCK, EMPTY, BLUE, EMPTY, EMPTY, EMPTY, BLOCK],
    [RED, BLOCK, EMPTY, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK],
    [EMPTY, BLOCK, EMPTY, RED, EMPTY, EMPTY, EMPTY, BLOCK],
    [EMPTY, BLOCK, BLUE, BLOCK, RED, BLOCK, EMPTY, BLOCK],
    [EMPTY, BLUE, EMPTY, RED, EMPTY, BLUE, EMPTY, BLOCK],
    [BLOCK, BLOCK, BLUE, BLOCK, BLUE, BLOCK, RED, BLOCK],
    [BLOCK, BLOCK, EMPTY, RED, EMPTY, BLUE, EMPTY, STARTRED],
]
export const puzzles: Record<string, (string | null)[][]> =
{
    "2025-3-26": [
        [BLOCK, BLOCK, BLOCK, BLOCK, RED, EMPTY, EMPTY, STARTBLUE],
        [BLOCK, RED, EMPTY, EMPTY, EMPTY, BLOCK, EMPTY, BLOCK],
        [BLOCK, EMPTY, BLOCK, BLUE, EMPTY, BLOCK, EMPTY, BLOCK],
        [BLOCK, EMPTY, EMPTY, EMPTY, RED, RED, EMPTY, BLOCK],
        [BLOCK, EMPTY, BLOCK, BLOCK, EMPTY, BLOCK, EMPTY, BLOCK],
        [BLOCK, BLUE, BLOCK, BLOCK, EMPTY, RED, EMPTY, BLOCK],
        [BLOCK, RED, EMPTY, EMPTY, BLUE, BLOCK, EMPTY, BLOCK],
        [BLOCK, BLOCK, BLOCK, RED, BLOCK, BLOCK, EMPTY, BLOCK],
        [BLOCK, BLOCK, RED, EMPTY, EMPTY, EMPTY, BLUE, BLOCK],
        [BLOCK, BLOCK, EMPTY, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK],
        [ENDRED, EMPTY, BLUE, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK],
    ],
    "2025-3-27": [
        [BLOCK, BLOCK, BLOCK, BLOCK, BLUE, EMPTY, EMPTY, STARTRED],
        [BLOCK, BLUE, EMPTY, EMPTY, EMPTY, BLOCK, EMPTY, BLOCK],
        [BLOCK, EMPTY, BLOCK, EMPTY, EMPTY, BLOCK, EMPTY, BLOCK],
        [BLOCK, EMPTY, EMPTY, EMPTY, RED, EMPTY, EMPTY, BLOCK],
        [BLOCK, EMPTY, BLOCK, BLOCK, EMPTY, BLOCK, EMPTY, BLOCK],
        [BLOCK, EMPTY, BLOCK, BLOCK, EMPTY, RED, EMPTY, BLOCK],
        [BLOCK, RED, EMPTY, EMPTY, BLUE, BLOCK, EMPTY, BLOCK],
        [BLOCK, BLOCK, BLOCK, BLUE, BLOCK, BLOCK, EMPTY, BLOCK],
        [BLOCK, BLOCK, BLUE, EMPTY, EMPTY, EMPTY, RED, BLOCK],
        [BLOCK, BLOCK, EMPTY, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK],
        [ENDBLUE, EMPTY, RED, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK],
    ],
    "2025-3-28": [
        [BLOCK, BLOCK, EMPTY, RED, EMPTY, BLUE, EMPTY, ENDRED],
        [BLOCK, BLOCK, EMPTY, BLOCK, BLUE, BLOCK, RED, BLOCK],
        [EMPTY, BLUE, EMPTY, RED, EMPTY, EMPTY, EMPTY, BLOCK],
        [EMPTY, BLOCK, RED, BLOCK, RED, BLOCK, EMPTY, BLOCK],
        [EMPTY, BLOCK, EMPTY, BLUE, EMPTY, EMPTY, EMPTY, BLOCK],
        [RED, BLOCK, EMPTY, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK],
        [EMPTY, BLOCK, EMPTY, RED, EMPTY, EMPTY, EMPTY, BLOCK],
        [EMPTY, BLOCK, BLUE, BLOCK, RED, BLOCK, EMPTY, BLOCK],
        [EMPTY, BLUE, EMPTY, RED, EMPTY, BLUE, EMPTY, BLOCK],
        [BLOCK, BLOCK, BLUE, BLOCK, BLUE, BLOCK, RED, BLOCK],
        [BLOCK, BLOCK, EMPTY, RED, EMPTY, BLUE, EMPTY, STARTRED],
    ]


}